name: Generate fees analysis DOCX

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download PPTX from raw URL
        run: |
          mkdir -p input
          curl -L "https://raw.githubusercontent.com/archrivalexe/temp20250823/main/%E5%AD%A6%E8%B4%B9.pptx" -o "input/学费.pptx"

      - name: Generate DOCX
        run: |
          python scripts/generate_fees_doc.py \
            --input "input/学费.pptx" \
            --output "docs/国内外著名大学心理学系硕士项目费用分析.docx"

      - name: Commit generated DOCX
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "docs/国内外著名大学心理学系硕士项目费用分析.docx"
          git commit -m "chore(docs): generate fees analysis doc from PPTX" || echo "No changes to commit"
          git push